# Generated by Django 5.0.6 on 2024-08-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Awaiting payment', 'Awaiting payment'), ('Confirmed', 'Confirmed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Returned', 'Returned')], default='Pending', max_length=20),
        ),
    ]
