# Generated by Django 5.0.6 on 2024-08-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0003_order_discount_price_order_final_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount_price',
        ),
        migrations.AddField(
            model_name='order',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
