# Generated by Django 5.0.6 on 2024-09-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0006_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
