# Generated by Django 5.0.6 on 2024-09-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0007_order_order_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
