# Generated by Django 5.0.6 on 2024-09-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0009_return'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='description',
        ),
        migrations.AddField(
            model_name='return',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
