# Generated by Django 5.0.6 on 2024-09-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0010_remove_return_description_return_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='coupon_offer',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
