# Generated by Django 5.0.6 on 2024-09-09 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0011_orderitem_coupon_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='paid_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
