# Generated by Django 5.0.6 on 2024-09-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0012_orderitem_paid_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.IntegerField(default=0),
        ),
    ]
