# Generated by Django 5.0.6 on 2024-09-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0013_order_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('creditCard', 'Credit Card'), ('Razopay ', 'Razopay'), ('cashOnDelivery', 'Cash on Delivery')], max_length=20),
        ),
    ]
