# Generated by Django 5.0.6 on 2024-12-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0015_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_offer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
