# Generated by Django 5.0.6 on 2024-08-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='colour_code',
            field=models.CharField(default='default_color'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variant_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
