# Generated by Django 5.0.6 on 2024-08-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='offer_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
