# Generated by Django 5.0.6 on 2024-08-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_offer_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
